"""Command line: python -m escalate <command>

  setup      pull the pinned models through Ollama and write/verify data/models.lock.json
  crawl      freeze a snapshot of the documentation site (refuses to overwrite; --force for a new version)
  verify     re-hash the frozen snapshot against data/snapshot/SNAPSHOT_MANIFEST.json
  chunk      split the snapshot into chunks
  qa         FictionalQA-style generation + blind/informed filter
  index      embed chunks
  tasks      build frozen task records from tasks/catalog.json (fork check + blind probe), the sets,
             the study text and the participant worksheet
  worksheet  print and write the block/task assignment for participants 1..N (default 15) and check its balance
  matching   per-task matching statistics (page words, passage words, query-passage overlap) -> data/tasks/_matching.json
  catalog    regenerate Assets/checkpoint2/task_catalog.md from the catalog, records and fork-check log
  all        crawl, chunk, qa, index, tasks
  rebuild    chunk, qa, index, tasks from the committed snapshot (no network crawl)
  ask        run the agent once:  python -m escalate ask "question" ["situation"]
  serve      start the playground at http://127.0.0.1:8567
"""
import json
import sys

from .common import LOCK_FILE, load_config, write_json


def setup():
    from . import llm
    cfg = load_config()
    locked = json.loads(LOCK_FILE.read_text(encoding="utf-8")) if LOCK_FILE.exists() else None
    found = {}
    for role, name in cfg["models"].items():
        print(f"pulling {name} ...")
        llm.pull(name)
        found[name] = {"role": role, "digest": llm.digest(name)}
    if locked:
        bad = [n for n, m in found.items() if locked["models"].get(n, {}).get("digest") != m["digest"]]
        if bad:
            print("WARNING: local model digests differ from data/models.lock.json for:", ", ".join(bad))
            print("Cached outputs will still replay exactly; new (uncached) calls may differ.")
        else:
            print("model digests match data/models.lock.json")
    else:
        write_json(LOCK_FILE, {"ollama_version": llm.version(), "models": found})
        print(f"wrote {LOCK_FILE}")
    write_model_versions(cfg, locked or json.loads(LOCK_FILE.read_text(encoding="utf-8")))


def write_model_versions(cfg, lock):
    """Runbook Section 1: MODEL_VERSIONS.md names every model, its role and digest, and the
    fork-check configuration, from the committed lock file and config.json."""
    import platform
    llm_name, emb = cfg["models"]["llm"], cfg["models"]["embed"]
    lines = [
        "# Model versions (generated by `python -m escalate setup`; do not edit by hand)", "",
        f"Runtime: Ollama {lock.get('ollama_version')} (lock file); pipeline Python {platform.python_version()}.", "",
        "| Role | Model | Digest |", "|---|---|---|",
        f"| Sub-step planner | `{llm_name}` | `{lock['models'][llm_name]['digest']}` |",
        f"| Fork judge | `{llm_name}` | same |",
        f"| QA generation and contamination filter (blind/informed) | `{llm_name}` | same |",
        f"| Embeddings | `{emb}` | `{lock['models'][emb]['digest']}` |", "",
        "Decoding for every LLM call: " + ", ".join(f"{k}={v}" for k, v in cfg["llm_options"].items()) + ".", "",
        "Fork-check configuration (runbook Section 4): "
        f"top-k = {cfg['retrieval']['k']}; margin threshold = {cfg['agent']['fork_margin']} (top-1 minus top-2 cosine); "
        "fires only when the margin is at or below the threshold AND the LLM judge says yes with at least two options "
        "grounded in the retrieved passages; a task additionally requires the grounded options to match the authored fork.",
    ]
    from .common import ROOT
    (ROOT / "MODEL_VERSIONS.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("wrote MODEL_VERSIONS.md")


def main(argv):
    if not argv or argv[0] in ("-h", "--help", "help"):
        print(__doc__)
        return
    cmd = argv[0]
    if cmd == "setup":
        setup()
    elif cmd == "crawl":
        from . import crawl
        crawl.run(force="--force" in argv)
    elif cmd == "verify":
        from . import crawl
        sys.exit(0 if crawl.verify() else 1)
    elif cmd in ("chunk", "qa", "index", "tasks", "matching"):
        from importlib import import_module
        import_module(f".{cmd}", __package__).run()
    elif cmd == "worksheet":
        from . import rotation
        rotation.run(int(argv[1]) if len(argv) > 1 else 15)
    elif cmd == "catalog":
        from . import catalog_report
        from .common import ROOT
        out = catalog_report.build(ROOT.parent / "Assets" / "checkpoint2" / "task_catalog.md")
        print(f"wrote {out}")
    elif cmd in ("all", "rebuild"):
        from . import crawl, chunk, qa, index, tasks
        if cmd == "all":
            crawl.run(force="--force" in argv)
        chunk.run()
        qa.run()
        index.run(force="--force" in argv)
        tasks.run()
    elif cmd == "ask":
        from . import agent
        rec = agent.run(argv[1], argv[2] if len(argv) > 2 else None)
        print(json.dumps(rec, indent=2, ensure_ascii=False))
    elif cmd == "serve":
        from .server import serve
        serve(int(argv[1]) if len(argv) > 1 else 8567)
    else:
        print(f"unknown command: {cmd}\n{__doc__}")
        sys.exit(2)


if __name__ == "__main__":
    main(sys.argv[1:])
